<?php

namespace Database\Seeders;

use App\Enums\RealEstate\DirectionEnum;
use App\Enums\RealEstate\FurnitureStatusEnum;
use App\Enums\RealEstate\LegalStatusEnum;
use App\Enums\RealEstate\PriceUnitEnum;
use App\Enums\RealEstate\ProjectStatusEnum;
use App\Enums\RealEstate\TransactionTypeEnum;
use App\Models\Project;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'name' => 'Vinhomes Grand Park - Phân khu The Rainbow',
                'catalogue_id' => 2,
                'type_code' => 'can_ho_chung_cu',
                'property_group' => 'apartment',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                // Địa chỉ cũ (3 cấp)
                'province_code' => 'ho_chi_minh',
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_code' => 'quan_9',
                'district_name' => 'Quận 9',
                'ward_code' => 'phuong_long_thanh_my',
                'ward_name' => 'Phường Long Thạnh Mỹ',
                // Địa chỉ mới (2 cấp - After 1/7)
                'province_new_code' => 'ho_chi_minh',
                'province_new_name' => 'Thành phố Hồ Chí Minh',
                'ward_new_code' => 'phuong_long_thanh_my',
                'ward_new_name' => 'Phường Long Thạnh Mỹ',
                'address' => '102, Nguyễn Xiển',
                'price' => 2.5,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 2500000000,
                'area' => 59,
                'direction' => DirectionEnum::DONG_NAM->value,
                'legal_status' => LegalStatusEnum::SO_HONG->value,
                'furniture_status' => FurnitureStatusEnum::BASIC->value,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floors' => 35,
                'floor_number' => '15',
                'extra_fields' => [
                    'block_name' => 'S1.01',
                    'apartment_code' => 'S1.01-1505',
                ],
                'is_featured' => 1,
            ],
            [
                'name' => 'Nhà mặt phố Nguyễn Huệ Commercial',
                'catalogue_id' => 6,
                'type_code' => 'nha_mat_pho',
                'property_group' => 'house',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                'province_code' => 'ho_chi_minh',
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_code' => 'quan_1',
                'district_name' => 'Quận 1',
                'ward_code' => 'phuong_ben_nghe',
                'ward_name' => 'Phường Bến Nghé',
                'address' => '22, Nguyễn Huệ',
                'price' => 150,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 150000000000,
                'area' => 120,
                'width' => 8,
                'length' => 15,
                'floors' => 5,
                'extra_fields' => [
                    'frontage' => 8,
                    'road_width' => 60,
                ],
                'is_hot' => 1,
            ],
            [
                'name' => 'Biệt thự Premier Village Danang Resort',
                'catalogue_id' => 5,
                'type_code' => 'biet_thu_lien_ke',
                'property_group' => 'house',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                'province_code' => 'da_nang',
                'province_name' => 'Thành phố Đà Nẵng',
                'district_code' => 'quan_ngu_hanh_son',
                'district_name' => 'Quận Ngũ Hành Sơn',
                'ward_code' => 'phuong_khue_my',
                'ward_name' => 'Phường Khuê Mỹ',
                'address' => '99, Võ Nguyên Giáp',
                'price' => 45,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 45000000000,
                'area' => 350,
                'area_land' => 350,
                'area_use' => 120,
                'direction' => DirectionEnum::DONG->value,
                'legal_status' => LegalStatusEnum::SO_DO->value,
                'furniture_status' => FurnitureStatusEnum::FULL->value,
                'bedrooms' => 4,
                'bathrooms' => 4,
                'extra_fields' => [],
                'video_url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'virtual_tour_url' => 'https://my.matterport.com/show/?m=example',
            ],
            [
                'name' => 'Đất nền Hưng Thịnh Garden - Sổ đỏ trao tay',
                'catalogue_id' => 8,
                'type_code' => 'dat_nen_du_an',
                'property_group' => 'land',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                'province_code' => 'long_an',
                'province_name' => 'Tỉnh Long An',
                'district_code' => 'huyen_can_giuoc',
                'district_name' => 'Huyện Cần Giuộc',
                'ward_code' => 'xa_long_hau',
                'ward_name' => 'Xã Long Hậu',
                'address' => 'Lô A1, KDC Long Hậu',
                'price' => 25,
                'price_unit' => PriceUnitEnum::PER_M2->value,
                'price_vnd' => 2500000, 
                'area' => 100,
                'legal_status' => LegalStatusEnum::SO_DO->value,
                'extra_fields' => [
                    'land_type' => 'ONT',
                    'zoning' => 'Dân cư hiện hữu',
                ],
            ],
            [
                'name' => 'Căn hộ The Matrix One - View hồ điều hòa',
                'catalogue_id' => 15,
                'type_code' => 'can_ho_chung_cu',
                'property_group' => 'apartment',
                'transaction_type' => TransactionTypeEnum::RENT->value,
                'province_code' => 'ha_noi',
                'province_name' => 'Thành phố Hà Nội',
                'district_code' => 'quan_nam_tu_liem',
                'district_name' => 'Quận Nam Từ Liêm',
                'ward_code' => 'phuong_me_tri',
                'ward_name' => 'Phường Mễ Trì',
                'address' => 'Số 1, Lê Đức Thọ',
                'price' => 18,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 18000000,
                'area' => 87,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'floor_number' => '28',
                'furniture_status' => FurnitureStatusEnum::FULL->value,
                'extra_fields' => [
                    'management_fee' => 15000,
                ],
            ],
            [
                'name' => 'Văn phòng Bitexco Financial Tower',
                'catalogue_id' => 22,
                'type_code' => 'van_phong',
                'property_group' => 'commercial',
                'transaction_type' => TransactionTypeEnum::RENT->value,
                'province_code' => 'ho_chi_minh',
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_code' => 'quan_1',
                'district_name' => 'Quận 1',
                'ward_code' => 'phuong_ben_nghe',
                'ward_name' => 'Phường Bến Nghé',
                'address' => '2, Hải Triều',
                'price' => 45,
                'price_unit' => PriceUnitEnum::PER_M2_MONTH->value,
                'price_vnd' => 45 * 25000,
                'area' => 500,
                'extra_fields' => [
                    'space_type' => 'Văn phòng hạng A',
                ],
            ],
            [
                'name' => 'Phòng trọ Blue Home - Thủ Đức',
                'catalogue_id' => 21,
                'type_code' => 'nha_tro_phong_tro',
                'property_group' => 'room',
                'transaction_type' => TransactionTypeEnum::RENT->value,
                'province_code' => 'ho_chi_minh',
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_code' => 'thanh_pho_thu_duc',
                'district_name' => 'Thành phố Thủ Đức',
                'ward_code' => 'phuong_linh_trung',
                'ward_name' => 'Phường Linh Trung',
                'address' => '45, Đường số 7',
                'price' => 3.5,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 3500000,
                'area' => 25,
                'extra_fields' => [
                    'electricity_price' => 3500,
                    'water_price' => 15000,
                    'deposit_months' => 1,
                ],
                'has_wifi' => 1,
                'has_parking' => 1,
            ],
            [
                'name' => 'Dự án Aqua City - Khu đô thị mới',
                'catalogue_id' => 30,
                'type_code' => 'khu_do_thi_moi',
                'property_group' => 'project',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                'province_code' => 'dong_nai',
                'province_name' => 'Tỉnh Đồng Nai',
                'district_code' => 'thanh_pho_bien_hoa',
                'district_name' => 'Thành phố Biên Hòa',
                'ward_code' => 'xa_long_hung',
                'ward_name' => 'Xã Long Hưng',
                'address' => 'Hương lộ 2, Xã Long Hưng',
                'price' => 6.5,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 6500000000,
                'area' => 110,
                'is_project' => 1,
                'extra_fields' => [
                    'developer_name' => 'Novaland',
                    'total_units' => 16000,
                    'progress_pct' => 45,
                ],
            ],
            [
                'name' => 'Nhà vườn Cố Đô - Hương Trà sáp nhập',
                'catalogue_id' => 4,
                'type_code' => 'nha_rieng',
                'property_group' => 'house',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                // Địa chỉ cũ
                'province_code' => 'thua_thien_hue',
                'province_name' => 'Tỉnh Thừa Thiên Huế',
                'district_code' => 'thi_xa_huong_tra',
                'district_name' => 'Thị xã Hương Trà',
                'ward_code' => 'phuong_huong_ho',
                'ward_name' => 'Phường Hương Hồ',
                // Địa chỉ mới (Sáp nhập TP Huế)
                'province_new_code' => 'thua_thien_hue',
                'province_new_name' => 'Tỉnh Thừa Thiên Huế',
                'ward_new_code' => 'phuong_huong_ho',
                'ward_new_name' => 'Phường Hương Hồ',
                'address' => '15, Hương Hồ',
                'price' => 3.2,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 3200000000,
                'area' => 150,
                'width' => 10,
                'direction' => DirectionEnum::BAC->value,
                'legal_status' => LegalStatusEnum::SO_DO->value,
                'extra_fields' => [
                    'frontage' => 10,
                    'year_built' => 2020,
                ],
            ],
            [
                'name' => 'Sun Harbor Shophouse Quy Nhơn',
                'catalogue_id' => 7,
                'type_code' => 'shophouse',
                'property_group' => 'house',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                'province_code' => 'binh_dinh',
                'province_name' => 'Tỉnh Bình Định',
                'district_code' => 'thanh_pho_quy_nhon',
                'district_name' => 'Thành phố Quy Nhơn',
                'ward_code' => 'phuong_ghenh_rang',
                'ward_name' => 'Phường Ghềnh Ráng',
                'address' => 'Khu Hải Giang',
                'price' => 12.5,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 12500000000,
                'area' => 108,
                'floors' => 4,
                'extra_fields' => [
                    'road_width' => 15,
                ],
            ],
            [
                'name' => 'Farmstay Đất Đỏ - Bảo Lâm',
                'catalogue_id' => 10,
                'type_code' => 'trang_trai_nghi_duong',
                'property_group' => 'land',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                'province_code' => 'lam_dong',
                'province_name' => 'Tỉnh Lâm Đồng',
                'district_code' => 'huyen_bao_lam',
                'district_name' => 'Huyện Bảo Lâm',
                'ward_code' => 'xa_loc_ngai',
                'ward_name' => 'Xã Lộc Ngãi',
                'address' => '88, Xã Lộc Ngãi',
                'price' => 850,
                'price_unit' => PriceUnitEnum::PER_M2->value,
                'price_vnd' => 850000000,
                'area' => 1000,
                'extra_fields' => [
                    'land_type' => 'CLN',
                    'zoning' => 'Quy hoạch đất ở',
                ],
            ],
            [
                'name' => 'Kho xưởng Amata II - Thuê dài hạn',
                'catalogue_id' => 24,
                'type_code' => 'kho_xuong',
                'property_group' => 'commercial',
                'transaction_type' => TransactionTypeEnum::RENT->value,
                'province_code' => 'dong_nai',
                'province_name' => 'Tỉnh Đồng Nai',
                'district_code' => 'thanh_pho_bien_hoa',
                'district_name' => 'Thành phố Biên Hòa',
                'ward_code' => 'phuong_long_binh',
                'ward_name' => 'Phường Long Bình',
                'address' => 'Lô 12, KCN Amata',
                'price' => 5,
                'price_unit' => PriceUnitEnum::PER_M2_MONTH->value,
                'price_vnd' => 125000,
                'area' => 2500,
                'extra_fields' => [
                    'road_width' => 25,
                ],
                'is_urgent' => 1,
            ],
            [
                'name' => '[DRAFT] Căn hộ chung cư mẫu kiểm thử',
                'catalogue_id' => 2,
                'type_code' => 'can_ho_chung_cu',
                'property_group' => 'apartment',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                'province_code' => 'ho_chi_minh',
                'province_name' => 'Thành phố Hồ Chí Minh',
                'district_code' => 'quan_1',
                'district_name' => 'Quận 1',
                'ward_code' => 'phuong_ben_nghe',
                'ward_name' => 'Phường Bến Nghé',
                'address' => '99, Nguyễn Du',
                'price' => 1,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 1000000000,
                'area' => 50,
                'status' => ProjectStatusEnum::DRAFT->value,
                'publish' => 1,
                'extra_fields' => [],
            ],
            [
                'name' => 'Nhà mặt ngõ thương lượng trực tiếp',
                'catalogue_id' => 4,
                'type_code' => 'nha_rieng',
                'property_group' => 'house',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                'province_code' => 'ha_noi',
                'province_name' => 'Thành phố Hà Nội',
                'district_code' => 'quan_ba_dinh',
                'district_name' => 'Quận Ba Đình',
                'ward_code' => 'phuong_phuc_xa',
                'ward_name' => 'Phường Phúc Xá',
                'address' => '12, Ngõ Đội Cần',
                'price' => 0,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 0,
                'price_negotiable' => 1,
                'area' => 45,
                'width' => 4,
                'extra_fields' => [
                    'road_width' => 2.5,
                ],
            ],
            [
                'name' => 'Grand Bay Halong - View Vịnh',
                'catalogue_id' => 11,
                'type_code' => 'condotel',
                'property_group' => 'apartment',
                'transaction_type' => TransactionTypeEnum::SALE->value,
                'province_code' => 'quang_ninh',
                'province_name' => 'Tỉnh Quảng Ninh',
                'district_code' => 'thanh_pho_ha_long',
                'district_name' => 'Thành phố Hạ Long',
                'ward_code' => 'phuong_bai_chay',
                'ward_name' => 'Phường Bãi Cháy',
                'address' => 'A2, Bán đảo 3',
                'price' => 3.5,
                'price_unit' => PriceUnitEnum::TOTAL->value,
                'price_vnd' => 3500000000,
                'area' => 42,
                'direction' => DirectionEnum::NAM->value,
                'floor_number' => '10',
                'extra_fields' => [
                    'apartment_code' => 'GB-102',
                ],
                'meta_title' => 'Condotel Grand Bay Hạ Long - Đầu tư 2024',
                'meta_desc' => 'Sở hữu căn hộ nghỉ dưỡng Condotel Grand Bay view trọn Vịnh Hạ Long.',
                'focus_keyword' => 'grand bay halong, bds ha long',
            ],
        ];

        foreach ($projects as $project) {
            $slug = Str::slug($project['name']);
            
            Project::updateOrCreate(
                ['slug' => $slug],
                array_merge($project, [
                    'slug' => $slug,
                    'status' => $project['status'] ?? ProjectStatusEnum::PUBLISHED->value,
                    'publish' => $project['publish'] ?? 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ])
            );
        }
    }
}
